# Generated by Django 5.2.17 on 2026-08-05 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('youtube_url', models.URLField(verbose_name='URL de YouTube')),
                ('youtube_id', models.CharField(blank=True, help_text='Se extrae automáticamente de la URL.', max_length=20, verbose_name='ID de YouTube')),
                ('miniatura', models.ImageField(blank=True, help_text='Se descarga automáticamente de YouTube.', null=True, upload_to='videos/thumbnails/', verbose_name='Miniatura')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('destacado', models.BooleanField(default=False, verbose_name='Destacado')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['orden', '-id'],
            },
        ),
    ]
