# Generated by Django 5.2.17 on 2026-08-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='categoria',
            field=models.CharField(blank=True, help_text='Ej: Tutorial, Demostración, Vlog', max_length=100, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='video',
            name='duracion',
            field=models.CharField(blank=True, help_text='Ej: 12:34', max_length=20, verbose_name='Duración'),
        ),
    ]
