# Generated by Django 5.2.17 on 2026-08-05 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_categoria_video_duracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='video',
            name='duracion',
        ),
    ]
