# Generated by Django 5.2.17 on 2026-08-05 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('icono', models.CharField(blank=True, help_text='Código SVG o clase CSS (ej. fa-brands fa-python)', max_length=1000, verbose_name='Ícono (SVG o Clase)')),
                ('color', models.CharField(blank=True, help_text='Color hex, ej. #3776AB', max_length=50, verbose_name='Color')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Tecnología',
                'verbose_name_plural': 'Tecnologías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('resumen', models.TextField(max_length=500, verbose_name='Resumen')),
                ('descripcion_larga', models.TextField(blank=True, verbose_name='Descripción Larga')),
                ('imagen_principal', models.ImageField(upload_to='projects/', verbose_name='Imagen Principal')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='projects/logos/', verbose_name='Logo del Proyecto')),
                ('estado', models.CharField(choices=[('en_desarrollo', 'En Desarrollo'), ('completado', 'Completado'), ('mantenimiento', 'En Mantenimiento')], default='completado', max_length=50, verbose_name='Estado')),
                ('destacado', models.BooleanField(default=False, verbose_name='Destacado')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('fecha_creacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('url_demo', models.URLField(blank=True, verbose_name='URL Demo')),
                ('url_github', models.URLField(blank=True, verbose_name='URL GitHub')),
                ('url_cliente', models.URLField(blank=True, verbose_name='URL Cliente')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Description')),
                ('categorias', models.ManyToManyField(blank=True, related_name='proyectos', to='projects.category', verbose_name='Categorías')),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='proyectos', to='projects.technology', verbose_name='Tecnologías')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('imagen', models.ImageField(upload_to='projects/captures/', verbose_name='Imagen')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capturas', to='projects.project')),
            ],
            options={
                'verbose_name': 'Captura',
                'verbose_name_plural': 'Capturas',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
