# Generated by Django 5.2.17 on 2026-08-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='projects/banners/', verbose_name='Banner del Proyecto'),
        ),
        migrations.AddField(
            model_name='project',
            name='documentacion',
            field=models.FileField(blank=True, null=True, upload_to='projects/docs/', verbose_name='Documentación Técnica'),
        ),
        migrations.AddField(
            model_name='project',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='projects/pdfs/', verbose_name='PDF del Caso de Estudio'),
        ),
        migrations.AddField(
            model_name='project',
            name='problema',
            field=models.TextField(blank=True, verbose_name='El Problema'),
        ),
        migrations.AddField(
            model_name='project',
            name='resultados',
            field=models.TextField(blank=True, verbose_name='Resultados obtenidos'),
        ),
        migrations.AddField(
            model_name='project',
            name='solucion',
            field=models.TextField(blank=True, verbose_name='La Solución'),
        ),
        migrations.AddField(
            model_name='technology',
            name='nivel',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('devops', 'DevOps / Infraestructura'), ('database', 'Base de Datos'), ('framework', 'Framework / Librería'), ('lenguaje', 'Lenguaje de Programación'), ('otro', 'Otro')], default='lenguaje', max_length=50, verbose_name='Nivel / Tipo'),
        ),
    ]
