# Generated by Django 5.2.17 on 2026-08-05 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_banner_project_documentacion_project_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='documentacion',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='project',
            name='problema',
        ),
        migrations.RemoveField(
            model_name='project',
            name='resultados',
        ),
        migrations.RemoveField(
            model_name='project',
            name='solucion',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='nivel',
        ),
    ]
