# Generated by Django 5.2.17 on 2026-08-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_banner_remove_project_documentacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='imagen_principal',
        ),
        migrations.RemoveField(
            model_name='project',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='project',
            name='publicado',
        ),
        migrations.RemoveField(
            model_name='project',
            name='resumen',
        ),
        migrations.AddField(
            model_name='project',
            name='descripcion_corta',
            field=models.TextField(default='', max_length=500, verbose_name='Descripción Corta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='estado_publicacion',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='publicado', max_length=50, verbose_name='Estado de Publicación'),
        ),
        migrations.AddField(
            model_name='project',
            name='imagen_portada',
            field=models.ImageField(default='', upload_to='projects/', verbose_name='Imagen Principal / Portada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='miniatura_youtube',
            field=models.ImageField(blank=True, null=True, upload_to='projects/youtube_thumbs/', verbose_name='Miniatura Automática de YouTube'),
        ),
        migrations.AddField(
            model_name='project',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID de YouTube'),
        ),
        migrations.AddField(
            model_name='project',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Pega el enlace completo de YouTube. El sistema extraerá la miniatura y generará el iframe automáticamente.', verbose_name='Enlace de YouTube'),
        ),
        migrations.AlterField(
            model_name='project',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Marcar para mostrar en la página principal.', verbose_name='Destacado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='estado',
            field=models.CharField(choices=[('en_desarrollo', 'En Desarrollo'), ('produccion', 'Producción'), ('finalizado', 'Finalizado'), ('pausado', 'Pausado')], default='finalizado', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Determina el orden visual en la página principal (ej. 1, 2, 3...)', verbose_name='Orden'),
        ),
    ]
