# Generated by Django 5.2.17 on 2026-08-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_imagen_principal_remove_project_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='youtube_url',
            field=models.TextField(blank=True, help_text='Pega el enlace completo o el código <iframe> de YouTube. El sistema extraerá el video automáticamente.', verbose_name='Enlace o Iframe de YouTube'),
        ),
    ]
