# Generated by Django 5.2.17 on 2026-08-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Imagen Principal / Portada'),
        ),
        migrations.AlterField(
            model_name='project',
            name='youtube_url',
            field=models.TextField(help_text='Requerido. Pega el enlace completo o el código <iframe> de YouTube. El sistema extraerá el video automáticamente.', verbose_name='Enlace o Iframe de YouTube'),
        ),
    ]
