# Generated by Django 5.2.17 on 2026-08-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_principal', models.CharField(default='Construyendo el futuro', max_length=200)),
                ('subtitulo_destacado', models.CharField(default='línea por línea_', max_length=200)),
                ('descripcion', models.TextField(default='Creamos soluciones digitales robustas.')),
                ('imagen_hero', models.ImageField(blank=True, null=True, upload_to='core/')),
            ],
            options={
                'verbose_name': 'Configuración de Inicio',
                'verbose_name_plural': 'Configuración de Inicio',
            },
        ),
    ]
